definitions:
  steps:
    - step: &server-test
        name: Server tests
        image: ruby:2.7.8-buster
        script:
          - ./bin/install_local_test_solr.sh
          - ./bin/run_server_tests.sh
        services:
          - postgres
        caches:
          - bundler
    - step: &client-test
        name: Client tests
        image: node:18.13.0
        size: 2x
        script:
          - npm ci
          - npm run test:batch:1
          - npm run test:batch:2
          - npm run test:batch:3
          - npm run test:batch:4
          - npm run test:batch:5
          - npm run test:new -- --maxWorkers=2
          - npm run lint:run
        caches:
          - node
    - step: &push-branch
        script:
          - git push unicef@vs-ssh.visualstudio.com:v3/unicef/ICTD%20-%20Primero%20X%20DEV/primero $BITBUCKET_BRANCH
          - git push https://$primeroimstoken@github.com/primeroIMS/primero.git $BITBUCKET_BRANCH
  services:
    postgres:
      image: postgres:14.5
      variables:
        POSTGRES_DB: 'primero_test'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgrespassword'
  caches:
    bundler: ./vendor
pipelines:
  branches:
    maint_*:
      - step: *push-branch
    '{develop*,release-*,main}':
      - parallel:
        - step: *server-test
        - step: *client-test
      - step: *push-branch
  tags:
    v*:
      - step:
          script:
            - git push unicef@vs-ssh.visualstudio.com:v3/unicef/ICTD%20-%20Primero%20X%20DEV/primero $BITBUCKET_TAG
            - git push https://$primeroimstoken@github.com/primeroIMS/primero.git $BITBUCKET_TAG
  pull-requests:
    '**':
      - parallel:
        - step: *server-test
        - step: *client-test
