---
- name: 'Copy Primero deployment private SSH key to remote host'
  copy:
    dest: '/root/.ssh/primero_deployment_key'
    mode: 'u=rw,go='
    content: '{{ ssh_private_key }}'
  become: yes
  when: ssh_private_key is defined
  tags:
  - 'always'

- name: 'Checking for external certs on remote machine'
  stat:
    path: '/srv/primero{{ nginx_ssl_cert_path }}'
  register: external_certs_crt
  when: use_external_certs == 'true'
  tags:
  - 'always'

- name: 'Checking for external certs (key) on remote machine'
  stat:
    path: '/srv/primero{{ nginx_ssl_key_path }}'
  register: external_certs_key
  when: use_external_certs == 'true'
  tags:
  - 'always'

- name: 'Fail if no external certs on remote machine'
  fail: msg="Remote machine missing external certs"
  when: use_external_certs == 'true' and (not external_certs_crt.stat.exists or not external_certs_key.stat.exists)
  tags:
  - 'always'

- name: 'Pull Primero from Git'
  git:
    repo: '{{ primero_repo|default("https://github.com/primeroIMS/primero.git") }}'
    dest: '/srv/primero/'
    version: '{{ primero_repo_branch }}'
    key_file: '/root/.ssh/primero_deployment_key'
    accept_hostkey: 'yes'
  become: yes
  tags:
  - 'always'

- name: 'create the local.env file'
  template:
    src: local.env.j2
    dest: '/srv/primero/docker/local.env'
    mode: 'u=rw'
  become: yes
  tags:
  - 'never'
  - 'local-env'

- name: 'Merge overrides.env with local.env'
  ansible.builtin.shell: |
    if test -f "{{ env_override_path | default('/home/' + ansible_user + '/overrides.env') }}"; then
      cat {{ env_override_path }} | grep -vE "^#" > tmp0
      cat /srv/primero/docker/local.env >> tmp0

      awk -F "=" '!a[$1]++' tmp0 > tmp1 && mv tmp1 /srv/primero/docker/local.env && rm tmp0
    else
      echo "No overrides file"
    fi
  become: yes
  tags:
  - 'never'
  - 'localized-env'

- name: 'build the Docker containers'
  command: |
    ./build.sh all -t '{{ build_docker_tag }}' -r '{{ build_docker_container_registry }}' -l
  args:
    chdir: '/srv/primero/docker'
  tags:
  - 'never'
  - 'build'

- name: 'Pull Primero configuration from Git'
  git:
    repo: '{{ primero_configuration_repo }}'
    dest: '/srv/primero-configuration/'
    version: '{{ primero_configuration_repo_branch|default("main") }}'
    key_file: '/root/.ssh/primero_deployment_key'
    accept_hostkey: 'yes'
  when: primero_configuration_repo is defined
  become: yes
  tags:
  - 'never'
  - 'configure'

- name: Creating configuration dir
  file:
    path: /srv/primero-configuration
    state: directory
  become: yes
  tags:
  - 'never'
  - 'configure-localized'

- name: Extract config into /srv
  unarchive:
    src: /home/{{ ansible_user }}/primero-configuration.tar.gz
    dest: /srv/primero-configuration
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: primero_configuration_path is defined
  become: yes
  tags:
  - 'never'
  - 'configure-localized'

- name: 'configure Primero with a custom configuration'
  command: |
    ./compose.configure.sh /srv/primero-configuration/ '{{ primero_configuration_path }}'
  args:
    chdir: '/srv/primero/docker'
  environment:
    PRIMERO_TAG: '{{ primero_tag|default("latest") }}'
    PRIMERO_IMAGE_REPOSITORY: '{{ primero_image_repositroy|default("primeroims") }}'
    PRIMERO_DEPLOY_NODB: '{{ primero_deploy_nodb|default("false") }}'
    PRIMERO_POSTGRES_VERSION: '{{ primero_postgres_version }}'
  when: primero_configuration_path is defined
  become: yes
  tags:
  - 'never'
  - 'configure'
  - 'configure-localized'

- name: 'configure Primero with the default seeds'
  command: |
    ./compose.configure.sh
  args:
    chdir: '/srv/primero/docker'
  environment:
    PRIMERO_TAG: '{{ primero_tag|default("latest") }}'
    PRIMERO_IMAGE_REPOSITORY: '{{ primero_image_repositroy|default("primeroims") }}'
    PRIMERO_DEPLOY_NODB: '{{ primero_deploy_nodb|default("false") }}'
    PRIMERO_POSTGRES_VERSION: '{{ primero_postgres_version }}'
  when: primero_configuration_path is not defined
  tags:
  - 'never'
  - 'configure'
  - 'configure-localized'

- name: 'Pull docker images'
  command: |
    ./compose.prod.sh pull
  args:
    chdir: '/srv/primero/docker'
  environment:
    PRIMERO_TAG: '{{ primero_tag|default("latest") }}'
    PRIMERO_IMAGE_REPOSITORY: '{{ primero_image_repositroy|default("primeroims") }}'
    PRIMERO_DEPLOY_NODB: '{{ primero_deploy_nodb|default("false") }}'
    PRIMERO_POSTGRES_VERSION: '{{ primero_postgres_version }}'
  when: always_pull is defined
  become: yes
  tags:
  - 'never'
  - 'start'

- name: '(re)start the Docker containers'
  command: |
    ./compose.prod.sh up -d --force-recreate --no-build
  args:
    chdir: '/srv/primero/docker'
  environment:
    PRIMERO_TAG: '{{ primero_tag|default("latest") }}'
    PRIMERO_IMAGE_REPOSITORY: '{{ primero_image_repositroy|default("primeroims") }}'
    PRIMERO_DEPLOY_NODB: '{{ primero_deploy_nodb|default("false") }}'
    PRIMERO_POSTGRES_VERSION: '{{ primero_postgres_version }}'
  become: yes
  tags:
  - 'never'
  - 'start'

- name: 'create/update docker version file'
  copy:
    dest: '/srv/primero/docker-app-version.txt'
    content: '{{ primero_tag|default("latest") }}'
  become: yes
  tags:
  - 'never'
  - 'start'

- name: 'copy docker cleanup script'
  copy:
    dest: '/srv/primero/primero-docker-cleanup.sh'
    src: 'primero-docker-cleanup.sh'
    mode: 'u=rwx,go=rx'
  become: yes
  tags:
  - 'never'
  - 'start' 

- name: 'create cron entry for pruning docker images'
  cron:
    name: 'pruning docker images'
    special_time: daily
    job: /srv/primero/primero-docker-cleanup.sh
    user: root
  become: yes
  tags:
  - 'never'
  - 'start' 