---
version: '3'
services:
  postgres:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/postgres:${PRIMERO_TAG:-latest}-pg${PRIMERO_POSTGRES_VERSION:-14}'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - docker/defaults.env
      - docker/local.env
    restart: always
  application:
    depends_on:
      - solr
      - postgres
  worker:
    depends_on:
      - solr
      - postgres
