// 'Registered Cases'

// Hook used for handling side effects in functional components.
// Used for Fetching data when the component is mounted.
import { useEffect } from "react";
// This is used for managing application state in a Redux store.
import { useDispatch } from "react-redux";

// NOTE This library is deprecated and the Styles were not working with it, So the Styles are used without it.
// Import styles from a Material UI library.
// Utility for defining CSS styles in a React component.
// import makeStyles from "@material-ui/core/styles/makeStyles";

// Import functions for fetching data.
import { fetchRegisteredCases } from "../../action-creators";
// Import functions for selecting data.
import { getRegisteredCases } from "../../selectors";
// Import a custom library function.
import { useMemoizedSelector } from "../../../../../libs";

// Import styles for this component.
import css from "./styles.css"; // NOTE Used 'css' instead of 'styles' to avoid name conflict with 'const css'

// NOTE Deprecated Use
// Create a useStyles function to define and apply styles to ensure consistent styling to the component.
// const useStyles = makeStyles(styles);

// Define the main Component function.
const Component = () => {
  // NOTE Deprecated Use
  // Contains CSS classes generated by makeStyles, which can be used to style elements in the component.
  // const css = useStyles();

  // Get access to Redux's dispatch function to trigger actions.
  const dispatch = useDispatch();
  // Use the useMemoizedSelector function to get data from the Redux store.
  const data = useMemoizedSelector(state => getRegisteredCases(state));

  // Extract statistics from the data if it exists, otherwise set it to null.
  const stats = data.getIn(["data", "stats"]) ? data.getIn(["data", "stats"]).toJS() : null;

  // Use the useEffect hook to perform an action when the component is mounted.
  useEffect(() => {
    // Dispatch an action to fetch PercentageChildrenReceivedChildProtectionServices
    dispatch(fetchRegisteredCases());
  }, []);

  // Render the following JSX (JavaScript XML) content.
  return (
    <>
      {stats && (
        <>
          {/* Display a heading */}
          <h2>Registered Cases</h2>

          {/* Create a container for displaying statistics */}
          <div className={css.container}>
            {/* Render statistics cards for different protection concerns */}
            {/* Each card displays a percentage and the number of cases for a specific concern */}
            {/* Cards have different background colors for visual distinction */}

            <div className={css.card} style={{ backgroundColor: "rgb(255, 99, 132)" }} flat>
              <div className={css.perc}>
                {stats.violence.percentage}% ({stats.violence.cases})
              </div>
              <div className={css.text}>Violence</div>
            </div>

            <div className={css.card} style={{ backgroundColor: "rgb(54, 162, 235)" }} flat>
              <div className={css.perc}>
                {stats.exploitation.percentage}% ({stats.exploitation.cases})
              </div>
              <div className={css.text}>Exploitation</div>
            </div>

            <div className={css.card} style={{ backgroundColor: "rgb(128, 0, 128)" }} flat>
              <div className={css.perc}>
                {stats.neglect.percentage}% ({stats.neglect.cases})
              </div>
              <div className={css.text}>Neglect</div>
            </div>

            <div className={css.card} style={{ backgroundColor: "rgb(255, 205, 86)" }} flat>
              <div className={css.perc}>
                {stats.harmful_practices.percentage}% ({stats.harmful_practices.cases})
              </div>
              <div className={css.text}>Harmful practice(s)</div>
            </div>

            <div className={css.card} style={{ backgroundColor: "rgb(54, 170, 89)" }} flat>
              <div className={css.perc}>
                {stats.abuse.percentage}% ({stats.abuse.cases})
              </div>
              <div className={css.text}>Abuse</div>
            </div>

            <div className={css.card} style={{ backgroundColor: "rgb(294,140, 89)" }} flat>
              <div className={css.perc}>
                {stats.other.percentage}% ({stats.other.cases})
              </div>
              <div className={css.text}>Other</div>
            </div>
          </div>
        </>
      )}
    </>
  );
};

// Set a display name for the Component
Component.displayName = `RegisteredCases`;

// Export the Component so it can be used in other parts of the application.
export default Component;
